### ISSUE TITLE
Missing build dependency for aylurs-gtk-shell

### ISSUE THREAD

**Issue by fbwdotdev** [kir68k/xira#9]
The ebuild has dev-util/meson in the build dependencies, but shouldn't it be dev-build/meson?

**Comment by kir68k** [comment]
Oh true, those were last updated before the name change.
I haven't been too active recently for personal reasons, but I have time right now so I'll fix those, and test if it builds without any further changes.

**Comment by fbwdotdev** [comment]
I tried editing the ebuild in my local tree and it failed to build, I could provide my build log if you would like.

**Comment by kir68k** [comment]
Tried to fix this, on the configure phase I get node warnings related to networking, then the errors:
```js
npm ERR! code ENETUNREACH
npm ERR! errno ENETUNREACH
```
So despite it being a live ebuild portage still restricts internet access? I don't know what changed since I wrote that file for it to do this.
After that it fails to patch as the code must've changed since I wrote the warning suppression patch, so I tried to remove it:

Then `meson` runs (as there's no `|| die` on `npm intall`), and I get typescript errors about types:
```
FAILED: src/tsc-output
/usr/bin/tsc --outDir /var/tmp/portage/gnome-extra/ags-9999/work/ags-9999/build/tsc-out
../src/app.ts(1,17): error TS2307: Cannot find module 'gi://Gtk?version=3.0' or its corresponding type declarations.
../src/app.ts(2,17): error TS2307: Cannot find module 'gi://Gdk?version=3.0' or its corresponding type declarations.
../src/app.ts(3,17): error TS2307: Cannot find module 'gi://Gio' or its corresponding type declarations.
../src/app.ts(4,18): error TS2307: Cannot find module 'gi://GLib' or its corresponding type declarations.
../src/app.ts(115,47): error TS7006: Parameter '_' implicitly has an 'any' type.
../src/app.ts(115,50): error TS7006: Parameter 'section' implicitly has an 'any' type.
../src/app.ts(115,59): error TS7006: Parameter 'err' implicitly has an 'any' type.
../src/app.ts(144,14): error TS2339: Property 'application_id' does not exist on type 'App'
[>50 more of the same error...]
```
I *assume* this happens because npm can't fetch everything, which again is weird as it could before.

Not sure if I have the time right now to deal with how npm seems to work, unfortunately.
You can try editing further, I remember I added the gi-typescript-definitions lines to fix the type errors, but e.g. the AUR PKGBUILD for aylurs-gtk-shell-git do not have anything about it, so right now I really don't know how to fix this.

**Comment by kir68k** [comment]
Alright, I removed the dev-util/meson dependencies from all files as they're unnecessary, Meson gets pulled in through `inherit`.

Once I can be fully back to this, or you feel like editing it yourself, look at the [updated ebuild](https://github.com/kir68k/xira/blob/4d25b6c/gnome-extra/ags/ags-9999.ebuild). I also changed the package name to `gnome-extra/ags`.
For now it's in package.mask. I'd close this as the meson issue is fixed, but I'll keep it open due to the larger npm issue. I'll remove the package if I can't find a solution in time.

**Comment by kir68k** [comment]
@fbwdotdev I rewrote the ebuild into a versioned one, which compiles and installs properly for me: https://github.com/kir68k/xira/pull/11. I use normal GNOME now, and ags seems to be made for Hyprland, which I don't have installed.
If you're still interested you can try this PR locally and test it on Hyprland, and comment here.

**Comment by kir68k** [comment]
No response, will merge.
